### ISSUE TITLE
Configurar Disqus

### ISSUE THREAD

**Issue by paulodealmeida** [phpba/phpba.github.io#10]
Os comentarios dos posts usam o Disqus e precisa ser configurado para o usuario do phpba.

**Comment by gildasio** [comment]
Posso fazer isso?

Utilizaria o [arquivo que fiz](https://github.com/gjuniioor/gjuniioor.github.io/blob/master/_includes/disqus.html) para meu blog.

Só teria de alterar o disqus name. Daí registra com um e-mail do PHPBa ou com minha conta mesmo? Acho mais organizado e descentralizado a primeira opção. Mas fica ai a sugestão de backup :smiley:

**Comment by paulodealmeida** [comment]
Pode usar seu código com uma nova conta do phpba, só manda um email para a lista com a senha, se houver.

**Comment by gildasio** [comment]
Tem um e-mail do phpba? Se sim, criar por ele seria melhor. Se não, crio por minha conta de posso ir adicionando os moderadores que tiverem interesse.
