### ISSUE TITLE
Setting up PHP 7.3 connection correctly with PostgreSQL 9.6

### ISSUE THREAD

**Issue by urograndis** [phpba/phpba.github.io#110]
I’m configuring a virtual machine in Google Cloud Platform, accord below.
Virtual Machine: machine type: g1-small (1 vCPU, 1.7 GB memory); zone: us-central1-c; firewalls: Allow HTTP trafficAllow HTTPS traffic.
Operational System: CentOS Linux release 7.6.1810 (Core)
Web server: Apache/2.4.6 (CentOS);
PHP: PHP Version 7.3.6;
Database: PostgreSQL 9.6.13 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit.
Install PostgreSQL extensions
[gsuite@flora-vm ~]$ sudo yum install php-pgsql
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile 
* base: mirror.cogentco.com 
* epel: mirror.steadfastnet.com 
* extras: mirror.cogentco.com 
* remi-php70: mirror.team-cymru.com 
* remi-php73: mirror.team-cymru.com 
* remi-safe: mirror.team-cymru.com 
* updates: mirror.cogentco.com
Package php-pgsql-7.3.6-3.el7.remi.x86_64 already installed and latest version.
Nothing to do

Set up:
vi /etc/php.d/20-pgsql.ini 
; Enable pgsql extension module
extension=pgsql

vi /etc/php.d/30-pdo_pqsql.ini
; Enable pdo_pgsql extension module
extension=pdo_pgsql

Script to test php connection with database
<?php
//  Configure DB Parameters
$host = "sisflora.com.br";
$dbname = "sisflora";
$dbuser = "postgres";
$userpass = "********";
$con = pg_connect("host=$host dbname=$dbname user=$dbuser password=$userpass");
if (!$con) {
        die('Could not connect');
}
else {
        echo ("Connected to local DB");
}
?>
Running this script return
	Could not connect
Verifying the return on the phpinfo() function find this:
pdo_pgsql: 
PostgreSQL(libpq) version: 9.2.24
pgsql: 
PostgreSQL(libpq) version: 9.2.24 
PostgreSQL(libpq) version: PostgreSQL 9.2.24 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28), 64-bit
The sisflora database in PostgreSQL 9.6 it work normally when access from by the psql or pgAdmin4.
My question is, how to configure PHP 7.3.3 to read PostgreSQL 9.6 correctly, considering that the PHP connection recognized PostgreSQL 9.2?

**Comment by gildasio** [comment]
@urograndis here isn't the right place to post these requests. I recommend use a forum, mail list or irc channel to do that.
