### ISSUE TITLE
Guia de Contribuição

### ISSUE THREAD

**Issue by gildasio** [phpba/phpba.github.io#13]
Acredito que seria bacana criar um guia completo para quem quiser contribuir com o blog (e assim, pode servir para outros projetos). Minha ideia é fazer uma página para ficar indicada logo no cabeçalho das páginas, assim fica mais chamativo para novos autores/devs.

> Cheguei a comentar de leve isso em #12 e #1 . 

Já fiz um [post](http://gjuniioor.github.io/blog/contribuindo-projetos-open-source/) sobre contribuir assim em meu blog mas aqui seria algo mais direcionado e mais focado em git/github.

Então, o que acham?

**Comment by paulodealmeida** [comment]
Acho ótimo ter um guia a assim, mas não precisa ser tão detalhado com instruções de uso do GitHub. Gosto da abordagem da Globo.com, se você não sabe usar o Git e o GitHub, aprenda e depois faça o fork. Afinal, com o tempo existirão apenas forks para posts e não para alterações no blog.

**Comment by gwmoura** [comment]
Concordo com o @paulodealmeida, quem quiser contribuir vai ter que aprender Git.  
E concordo com o @gjuniioor, no ponto de escrever algum material para ajudar quem não sabe como contribuir (a comunidaade tem que ajudar os iniciantes  :smile:), mas daí podemos só referenciar o conteúdo. 

Algo +/- assim:

> Quer contribuir? Siga as intruções! - no cabeçalho das páginas
> Não sabe nada de git? Aprenda aqui! - na página de instruçoes

**Comment by gildasio** [comment]
Beleza! Então vou fazer isso e mando o PR. Vocês analisam e diz se está tranquilo. Qualquer coisa, comenta no PR que vou arrumando pra ficar ideal.

Gostei da ideia do @gwmoura, de linkar as coisas, mas acho interessante ter um post em que a pessoa "só" precise ler ele. Não são todos que tem curiosidade e vontade de estudar as coisas bem para poder contribuir.

Então vou pensar em fazer assim:

Conteúdo do Guia:
- BREVE instruções de uso do Git/Github
- Links para referência/aprender mais

> Seria mais um how to/guia mesmo que um artigo

**Comment by jonataa** [comment]
@gjuniioor acho interessante ajudar os iniciantes em git, mas com links externos pq seria um esforço absurdo criar algo relevante, principalmente nesse inicio em que temos muito para fazer. Um material sem qualidade pode frustra-la mais do que realmente ajudar. Esse esforço poderia estar na qualidade desses links externos =)

Sou a favor do "faça apenas o essecial agora e evolua depois".

Abraço, 

Jonata

**Comment by paulodealmeida** [comment]
A página do guia de postagem foi criada e está muito boa!
