### ISSUE TITLE
"Crawlear" artigos/blogs de integrantes do PHPBA

### ISSUE THREAD

**Issue by jonataa** [phpba/phpba.github.io#17]
Pessoal, 

Queria levantar uma questão, enquanto as coisas ainda estão no início. Pelo o que tenho acompanhando, a ideia do blog é ter artigos escritos por integrantes da comunidade, certo? Porém, alguns integrantes já possuem blogs, e quem escreve sabe o quanto é difícil reservar um tempo para escrever e postar algo novo.

A minha sugestão é, ao invés de criar postagens "diretas" no blog, pq não "crawlear" ou referenciar alguns posts de integrantes do PHPBA?

Acho que isso evitaria postagens duplicadas e diminuiria o esforço de ter que escrever em dois lugares diferentes. Tenho quase certeza que alguns (com seu pouco tempo livre) irão preferir postar em seu próprio blog do que no PHPBA.

Além disso, manteríamos o blog do PHPBA sempre atualizado! =)

Acho que os "posts diretos" poderiam existir e ser referentes a iniciativas (eventos, hangouts, discussões épicas, etc) do PHPBA, ou para aqueles que não tem interesse nenhum em criar seu próprio blog, mas acredito que esses sejam a excessão.

E ai, o que vcs acham?

**Comment by mlalbuquerque** [comment]
Por mim beleza. Agora é achar com fazer o crawling no Jekyll.

Em Qua, 10 de fev de 2016 15:01, Jonata Weber notifications@github.com
escreveu:

> Pessoal,
> 
> Queria levantar uma questão, enquanto as coisas ainda estão no início.
> Pelo o que tenho acompanhando, a ideia do blog é ter artigos escritos por
> integrantes da comunidade, certo? Porém, alguns integrantes já possuem
> blogs, e quem escreve sabe o quanto é difícil reservar um tempo para
> escrever e postar algo novo.
> 
> A minha sugestão é, ao invés de criar postagens "diretas" no blog, pq não
> "crawlear" ou referenciar alguns posts de integrantes do PHPBA?
> 
> Acho que isso evitaria postagens duplicadas e diminuiria o esforço de ter
> que escrever em dois lugares diferentes. Tenho quase certeza que alguns
> (com seu pouco tempo livre) irão preferir postar em seu próprio blog do que
> no PHPBA.
> 
> Além disso, manteríamos o blog do PHPBA sempre atualizado! =)
> 
> Acho que os "posts diretos" poderiam existir e ser referentes a
> iniciativas (eventos, hangouts, discussões épicas, etc) do PHPBA, ou para
> aqueles que não tem interesse nenhum em criar seu próprio blog, mas
> acredito que esses sejam a excessão.
> 
> E ai, o que vcs acham?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/phpba/phpba.github.io/issues/17.
> 
> ## 

# Marcio Albuquerque

Analista de Infra SERPRO
Celular - 88804994

**Comment by jonataa** [comment]
Quanto a isso, acho tranquilo. Depende do "como" será exibida a informação.

Um maneira seria criando um [datafile](http://jekyllrb.com/docs/datafiles/) com título, amostra do texto (com poucos caracteres), autor, link da postagem, etc, e commitar normalmente no repositório. Podemos criar esse arquivo manualmente através de PRs (o autor poderia mandar tb) ou automatizar utilizando o travis.io.

Nesse início, não vejo necessidade de automatizar, contato que seja apenas uma amostra do post original, a minha ideia é colocar um botão "Continue Lendo" e levar o usuário para o outro blog.

**Comment by mlalbuquerque** [comment]
Achei esses dois links. Vou testar aqui no meu fork.

http://import.jekyllrb.com/docs/installation/
http://import.jekyllrb.com/docs/wordpress/

Percebam que tem pra vários, como Blogger, Joomla, Drupal, etc.

**Comment by gildasio** [comment]
Acho bacana a ideia, mas teria de ser algo filtrado. Pelo que entendi, a ideia do _datafile_ parece bacana, uma vez que terá de subir o arquivo para linkar aqui. Ou seja, se o cara tem o blog pessoal e fala sobre várias outras coisas além de PHP (como é [meu caso](https://gjuniioor.github.io)) não vão cair todos os posts aqui.

Uma outra _"solução"_ que veria é o cara realmente mandar o post aqui e logo no início ter algo como:

> Artigo originalmente postado aqui: url_original_post

É algo que rola muito em locais como Viva o Linux e tal.

Bem, fica a ideia ai.

**Comment by mlalbuquerque** [comment]
Gosto mais desses ideias de postar pelo Github mesmo.

Em Qua, 10 de fev de 2016 16:07, Gildásio Júnior notifications@github.com
escreveu:

> Acho bacana a ideia, mas teria de ser algo filtrado. Pelo que entendi, a
> ideia do _datafile_ parece bacana, uma vez que terá de subir o arquivo
> para linkar aqui. Ou seja, se o cara tem o blog pessoal e fala sobre várias
> outras coisas além de PHP (como é meu caso https://gjuniioor.github.io)
> não vão cair todos os posts aqui.
> 
> Uma outra _"solução"_ que veria é o cara realmente mandar o post aqui e
> logo no início ter algo como:
> 
> Artigo originalmente postado aqui: url_original_post
> 
> É algo que rola muito em locais como Viva o Linux e tal.
> 
> Bem, fica a ideia ai.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/phpba/phpba.github.io/issues/17#issuecomment-182506978
> .
> 
> ## 

# Marcio Albuquerque

Analista de Infra SERPRO
Celular - 88804994

**Comment by jonataa** [comment]
Teríamos algumas limitações se postar todo o conteúdo no blog:
1. O cara terá que utilizar para Markdown, ou fazer a conversão (bem trabalhoso);
2. Se ele atualizar alguma informação no blog, terá que enviar essa informação para o nosso tb (considerando um processo manual, pois talvez seja inviável automatizar o crawler já que existem diversos hosting de blog);
3. A formatação do texto (hightlights, etc) pode não ficar legal se converter para o nosso, já que ele considerou a formatação dele;

Por isso que acho interessante apenas fazer referência ao blog dele com um botão "continue lendo".

**Comment by mlalbuquerque** [comment]
OK. E dá pra fazer isso com datafiles, né?

Em Qua, 10 de fev de 2016 19:06, Jonata Weber notifications@github.com
escreveu:

> Teríamos algumas limitações se postar todo o conteúdo no blog:
> 1. O cara terá que utilizar Markdown, ou fazer a conversão (bem
> trabalhoso);
> 2. Se ele atualizar alguma informação no blog, terá que enviar essa
> informação para o nosso tb (considerando um processo manual, pois talvez
> seja inviável automatizar o crawler já que existem diversos hosting de
> blog);
> 3. A formatação do texto (hightlights, etc) pode não ficar legal se
> converter para o nosso, já que ele considerou a formatação dele;
> 
> Por isso que acho interessante apenas fazer referência ao blog dele com um
> botão "continue lendo".
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/phpba/phpba.github.io/issues/17#issuecomment-182582037
> .
> 
> ## 

# Marcio Albuquerque

Analista de Infra SERPRO
Celular - 88804994

**Comment by jonataa** [comment]
Sim, tranquilamente. Seria algo assim:

_data/posts.yml

```
- title: Hello World
  text: Primeiro parágrafo do post...
  author: Foo Bar
  href: http://blog.author.com/link/to/post  

- title: Hello World 2
  text: Primeiro parágrafo do post...
  author: Foo Bar
  href: http://blog.author.com/link/to/post2
```

Pra chamar no template, seria assim:

```
<ul>
{% for post in site.data.posts %}
  <li>
    <a href="{{ post.href }}">
     <h2>{{ post.title }}</h2>
     <p>{{ post.text }}</p>
     <p>{{ post.author }}</p>
    </a>
  </li>
{% endfor %}
</ul>
```

**Comment by mlalbuquerque** [comment]
## Show de bola! Então cavalos assim. Muito bom.

# Marcio Albuquerque

Analista de Infra SERPRO
Celular - 88804994

**Comment by gildasio** [comment]
Bacana! Mas @jonataa , isso ficaria na página principal ou numa página em separado?

**Comment by mlalbuquerque** [comment]
Seria legal se fosse na principal é de forma transparente. Tem como unir os
dois arrays dentro do Liquid?

> ## 

# Marcio Albuquerque

Analista de Infra SERPRO
Celular - 88804994

**Comment by jonataa** [comment]
@gjuniioor Tem que ser transparente como @mlalbuquerque mencionou. O problema agora é fazer o merge com o Jekyll mantendo uma ordem cronológica da data de postagem (no PHPBA).

**Comment by gildasio** [comment]
Hoje tava pensando aqui, já que a pessoa terá que fazer o PR com o datafile, para facilitar nessa questão do loop, seria uma boa ela fazer o PR com o post mas colocar uma variável no post, algo como:

``` yaml
original: link_para_o_post
```

E caso essa variável esteja lá, o blog fazer um redirect para ele. Daí como conteúdo do post ela só coloca um paragráfo, para servir na preview do index.

O que acham?

**Comment by jonataa** [comment]
Excelente, Gildásio! Gostei da sugestão, faz sentido dessa maneira pra mim
tb.

Em seg, 15 de fev de 2016 às 15:29, Gildásio Júnior <
notifications@github.com> escreveu:
