### ISSUE TITLE
Criar a entrada CNAME apontando para GitHub

### ISSUE THREAD

**Issue by hugohenrique** [phpba/phpba.github.io#20]

**Comment by hugohenrique** [comment]
A alteração já foi feita, vamos aguardar a atualização.

**Comment by gildasio** [comment]
Criou para phpba.com.br ou blog.phpba.com.br ou algum outro?

**Comment by hugohenrique** [comment]
phpba.com.br

**Comment by gildasio** [comment]
http://www.phpba.com.br e http://blog.phpba.com.br levam para um 404 do Github. Isso é configuração passada ou foi a configuração de agora?
