### ISSUE TITLE
Criar link para o repositorio

### ISSUE THREAD

**Issue by paulodealmeida** [phpba/phpba.github.io#24]
No blog não tem nenhum link para o repositorio. Onde poderia colocar esse link?

**Comment by jonataa** [comment]
Pra pessoas contribuírem com artigos? Vc pode colocar um botão logo abaixo de "toda contribuição será bem vinda" dizendo: Envie-nos um artigo. Ou pode colocar aquela etiqueta no canto "fork me on github" levando pra o repositório.

**Comment by jonataa** [comment]
Ué, já fechou?

**Comment by paulodealmeida** [comment]
Vi que tem um link no final da página, é meio escondido mas existe.

**Comment by jonataa** [comment]
Pois é, eu vi, mas leva somento ao perfil. O ideal seria um link mais explícito fazendo o convite para novos artigos. Olha aí as etiquetas: https://github.com/blog/273-github-ribbons

Mas acho que o botão no meio do banner fique mais convidativo.

**Comment by paulodealmeida** [comment]
Era isso que eu estava pensando!!
Do lado direito vermelho ficaria ótimo.
