### ISSUE TITLE
README.md como post ou page

### ISSUE THREAD

**Issue by mlalbuquerque** [phpba/phpba.github.io#25]
E aí? O que acham de colocar o README como um post?? Poderia ser um post ou uma page de como trabalhar com os posts.

Seria bom comentar sobre os datafiles também.

**Comment by hugohenrique** [comment]
:+1:

**Comment by paulodealmeida** [comment]
Acho excelente @mlalbuquerque, colocar o readme como uma página, assim ficaria fixa.

**Comment by gildasio** [comment]
Essa é minha ideia do #13 , mas mal ai, enrolando demais né?!  :sweat_smile:

**Comment by paulodealmeida** [comment]
A página do guia de postagem foi criada e está muito boa!
