### ISSUE TITLE
Imagem do Fork me on Github

### ISSUE THREAD

**Issue by mlalbuquerque** [phpba/phpba.github.io#32]
A imagem do Fork no bando superior direito não deixa clicar o menu na versão mobile. Não testei ainda a versão desktop.

**Comment by gildasio** [comment]
Se colocar do lado esquerdo resolve, a meu ver. Tento fazer isso ou espera ver quem manja mais de mobile q eu? rs'

**Comment by paulodealmeida** [comment]
No desktop funciona. Vou abrir uma issue para mudar de lugar.

**Comment by gjuniioor** [comment]
Closed by #34

**Comment by gildasio** [comment]
Closed by #34
