### ISSUE TITLE
Criar uma seção de drafts

### ISSUE THREAD

**Issue by paulodealmeida** [phpba/phpba.github.io#40]
O que acham de criar uma seção de rascunhos com todos os pull requests dos drafts e antes de ir para a página principal, assim outros poderiam ver se está tudo ok.
Só não sei como fazer isso com o Jekyll.

**Comment by mlalbuquerque** [comment]
Não sei. Acho que o esquema de PR meio que já serve pra isso. Tá lá aberto.
Quem quiser, pode ver os PRs todos e dar pitaco.

Em Ter, 23 de fev de 2016 07:42, Paulo de Almeida notifications@github.com
escreveu:

> O que acham de criar uma seção de rascunhos com todos os pull requests dos
> drafts e antes de ir para a página principal, assim outros poderiam ver se
> está tudo ok.
> Só não sei como fazer isso com o Jekyll.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/phpba/phpba.github.io/issues/40.
> 
> ## 

# Marcio Albuquerque

Analista de Infra SERPRO
Celular - 071 98880 4994

**Comment by paulodealmeida** [comment]
Ok, acho melhor mesmo, assim fica centralizado.
