### ISSUE TITLE
Exibir nome do autor na listagem do post

### ISSUE THREAD

**Issue by cleristonos** [phpba/phpba.github.io#51]
Pessoal não seria interessante ter o nome do autor (preferencialmente um link) junto a data do post? Hoje preciso abrir o post para ver que o escreveu.

**Comment by gildasio** [comment]
Hm, lá na listagem dos posts mesmo, né? Talvez seja uma boa. Minha opinião é de que é tranquilo de se fazer, mas que por ser algo de comunidade, a ideia seria que a pessoa vá ver o post no interesse pelo título e descrição, pouco se importanto com quem redigiu o texto (até pq, quando tem o PR, a comunidade passa a dar sugestão e ajudar nisso também). Mas bem, fica ai aberto para outras opiniões e a depender de como for recebido, bota isso mesmo :)

**Comment by cleristonos** [comment]
Sim, na lista mesmo. Para apenas exibir o nome vi que é bem tranquilo de fazer, só não o fiz aguardando manifestações.

**Comment by gildasio** [comment]
Sim sim, é bem simples. A questão é ver se seria algo realmente bacana. Bem, esperando mais opiniões da galera.

**Comment by paulodealmeida** [comment]
Acho bom colocar o nome.

**Comment by gwmoura** [comment]
Eu não vejo nada de mais colocar o nome
