### ISSUE TITLE
Dificuldade de leitura abaixo do título

### ISSUE THREAD

**Issue by cleristonos** [phpba/phpba.github.io#52]
Pessoal o conteúdo (texto e ícones)  que ficam logo abaixo do título na página do post se misturam com a imagem de capa, dificulta a leitura principalmente porque temos azul sobre o azul e branco sobre branco.
![captura de tela de 2016-04-11 09 54 42](https://cloud.githubusercontent.com/assets/4993022/14427491/72de3a44-ffcb-11e5-8073-553231b7af6f.png)

PS: Pessoalmente eu gosto de saber quem estou lendo, antes mesmo de ler. E senti que não está intuitivo como em outros blogs os quais eu leio, identificar o author. Tendo em vista que esse não é um blog pessoal e temos post de várias pessoal poderíamos deixar isso mais evidente. Outras medidas seriam #51 e #53

**Comment by gildasio** [comment]
O bom da capa é que ela é móvel, ou seja, tem uma variável na página do post que o autor pode botar a imagem que ele quiser, a questão é que ainda concordo, acho que uma sombra ou tirar a cor que os ícones sofrem pelo link seria melhor, certo?

**Comment by cleristonos** [comment]
Pode alterar a opacidade do BG com css para melhorar a leitura independente de qualquer que seja capa

**Comment by gildasio** [comment]
Fiz algumas modificações aqui mas nenhuma delas me agradaram. Se puder editar de algo que fique bacana e submeter um pull request, é bem vindo! :D

**Comment by mvfsillva** [comment]
Seria bacana aplicar um efeito overlay(background com transparência) em cima da imagem, para que o texto fique mais nítido, o que acham?

**Comment by gildasio** [comment]
Acho isso massa, @mvfsilva, mas meus skills de front-end ... vou nem comentar. 

Fica aberto ai pra mandar tua sugestão :P

**Comment by paulodealmeida** [comment]
Vou fechar essa issue pois foi corrigido com o #62
