### ISSUE TITLE
Criar Feed

### ISSUE THREAD

**Issue by paulodealmeida** [phpba/phpba.github.io#55]
Que tal criar um feed para o blog?

**Comment by gwmoura** [comment]
Podemos usar um serviço como feedburner - https://feedburner.google.com e o jekyll tem um esquema de feed bem simples - http://jekyll.tips/tutorials/rss-feed/

**Comment by gildasio** [comment]
Se eu disser que já tem? :P 

http://phpba.com.br/feed

**Comment by paulodealmeida** [comment]
Massa @gjuniioor vou criar uma issue para colocar o link no blog

**Comment by gildasio** [comment]
Show, mais vantagem! Já cita onde acha bacana a localização.
