### ISSUE TITLE
adicionar botão para compartilhar no telegram

### ISSUE THREAD

**Issue by allanbarbosa** [phpba/phpba.github.io#69]
Estava pensando aqui em achar alguma forma para adicionar um botão para compartilhar as postagens nos grupos do telegram.

**Comment by allanbarbosa** [comment]
Achei a URL para compartilhamento.

https://telegram.me/share/url?url=http://phpba.com.br/2-phpeetup-programacao/&text=2-phpeetup-programacao

**Comment by paulodealmeida** [comment]
Maneiro, colocaria no post?

**Comment by allanbarbosa** [comment]
Sabe aonde fica os botão de compartilhar no twitter e facebook, embaixo do post, coloca do lado deles.

**Comment by gildasio** [comment]
Olha o #70  ai :)

Fiz o teste local e funcionou (pode olhar no grupo do PHPBA haha)

**Comment by allanbarbosa** [comment]
Se funcionou, show! Só da merge. Show de bola!!! Já estava aqui me batendo para enteder o Jekyll para alterar isso.

**Comment by gildasio** [comment]
Show! Merge feito e issue automaticamente fechada ( @paulodealmeida mostra isso na palestra hehe ) :D
