### ISSUE TITLE
Categorias em Post da Galera

### ISSUE THREAD

**Issue by gildasio** [phpba/phpba.github.io#74]
No post "Post da Galera" as categorias estão listadas de modo errado. Elas estão `categories: phpeetup, live, code`, sendo que a melhor forma seria em forma de lista:

``` yaml
categories:
    - phpeetup
    - live
    - code
```

> **OBS**: Não esqueça que não se deve usar TAB ali na identação, mas sim 4 spaces.

;)

**Comment by paulodealmeida** [comment]
Corrigido no #83
