### ISSUE TITLE
Meta informações do post

### ISSUE THREAD

**Issue by gildasio** [phpba/phpba.github.io#75]
Na resolução de uma issue que surgiu aqui, para mostrar o nome do autor na listagem dos posts:

![Print da listagem de posts](https://i.imgur.com/DVOZKCT.png)

Acabou que quebrou uma parte do layout na exibição do próprio post:

![Print da exibição de post](https://i.imgur.com/iJJKHrv.png)

Uma possível solução e já com uma feature seria adicionar um novo campo na exibição do post com a informação do tempo médio que levaria para ler esse post. Você pode até ver um [how to](https://indefiniteloop.com/blog/code/time-to-read-post-jekyll.html) de como fazer.

**Comment by paulodealmeida** [comment]
Bug corrigido.
