### ISSUE TITLE
Dockerfile para rodar jekyll

### ISSUE THREAD

**Issue by vinaocruz** [phpba/phpba.github.io#81]
Poderiamos criar um container com o ambiente já configurado para testar o jekyll localmente.

Que acham?

**Comment by gwmoura** [comment]
Achei uma ótima ideia

**Comment by paulodealmeida** [comment]
Acho excelente!! Eu uso essa receita para rodar meus projetos jekyll

docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll -it -p 127.0.0.1:4000:4000 jekyll/jekyll

**Comment by gildasio** [comment]
Tem [essa imagem aqui](https://hub.docker.com/r/starefossen/github-pages/) que parece funcionar legal, mas nunca testei ela.

Por incrível que pareça, hoje vou precisar testar. Daí já dou o feedback :)
